api_platform:
    title: Tropical Recipes API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
    eager_loading:
        max_joins: 10
        fetch_partial: true
        force_eager: false
