nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    allow_headers: ['Content-Type','Authorization']
  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200']
