nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    allow_credentials: true
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200']
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
      allow_credentials: true
